version: 2

sources:
  - name: censo_staging  # Nome que você usa dentro do {{ source('censo', '...') }}
    database: affable-envoy-482112-d9  # ID do seu projeto no Google Cloud
    schema: censo_staging  # Nome do Dataset no BigQuery
    tables:
      - name: stg_censo__dados_2024