version: 2

sources:
  - name: enem  # Nome que você usa dentro do {{ source('enem', '...') }}
    database: affable-envoy-482112-d9  # ID do seu projeto no Google Cloud
    schema: enem  # Nome do Dataset no BigQuery
    tables:
      - name: raw_enem_2024
      - name: raw_enem_results_2024